---
# tasks file for workstation_baseline
- name: Set workstation power settings
  win_shell: "powercfg {{ item.poweroption }} {{ item.time }}"
  loop:
    - { poweroption: '/change disk-timeout-dc', time: '0' }
    - { poweroption: '/change disk-timeout-ac', time: '0' }
    - { poweroption: '/change monitor-timeout-ac', time: '15' }
    - { poweroption: '/change monitor-timeout-dc', time: '15' }    
    - { poweroption: '/change standby-timeout-ac', time: '00' }
    - { poweroption: '/change standby-timeout-dc', time: '00' }
    #hibernate off so it doesnt create hibernate file 
    - { poweroption: '-h', time: 'off' }
#Disable UAC
# - name: turn UAC off
#   win_regedit:
#     path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system
#     name: EnableLUA
#     data: 0
#     type: dword
#     state: present
#   register: uac_result
# - name: reboot after disabling UAC
#   win_reboot:
#   when: uac_result is changed
#Disable firewall
- name: Disable firewall for Domain, Public and Private profiles
  win_firewall:
    state: disabled
    profiles:
      - Domain
      - Public
      - Private
#choco installs
- name: Manage 7zip
  win_chocolatey:
    name: 7zip
    state: present
  ignore_errors: yes
- name: Manage Chrome
  win_chocolatey:
    name: googlechrome
    state: present
  ignore_errors: yes
# One way to ensure the system is reliable just after a reboot, is to set WinRM to a delayed startup
# - name: Ensure WinRM starts when the system has settled and is ready to work reliably
#   win_service:
#     name: WinRM
#     start_mode: delayed
# - name: Rebooting for updates
#   win_reboot:
# - name: Install all security, critical, and rollup updates
#   win_updates:
#     category_names:
#         - SecurityUpdates
#         - CriticalUpdates
#         - UpdateRollups
#         - drivers
#         - updates
#         - Windows Defender
#         - Windows 10
#   ignore_errors: yes
# - name: Rebooting after updates
#   win_reboot:
