- name: Checking if scan result is present
  win_stat:
    path: "{{ malwarebytes_scan_file }}"
  register: scanfile
- name: calculating last run time 
  set_fact: 
    needtorun: "{{ ansible_date_time.epoch|int - scanfile.stat.lastwritetime|int}}"
  when: scanfile.stat.exists == true
- name: "Creating Directory"
  win_file:
    state: directory
    path: "{{ malwarebytes_path }}"
- name: Download Powershell Scanner
  win_get_url:
    url: "{{ malwarebytes_url }}"
    dest: "{{ malwarebytes_file }}"
    force: True 
- name: Running powershell scan 
  win_shell: "{{ malwarebytes_file }}"
  when: 
    - "needtorun|int > 86000"
- name: Gathering Scan Results 
  win_shell: Get-Content {{ malwarebytes_scan_file }}
  register: result1
- name: Process Scan Results
  set_fact:
    sr: "{{ result1.stdout | from_json }}" 
- name: Output of Scan Results
  debug:
    msg: 
      - "Threats Detected: {{ sr.threatsDetected }}"
      - "Scan End Time: {{ sr.sourceDetails.scanEndTime }}"