---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: windows10
    box: tas50/windows_10
    memory: 4096
    cpus: 2
    provider_options:
      gui: false

provisioner:
  name: ansible
  connection_options:
    sudo: False
    ansible_connection: winrm
    ansible_port: 55985
    ansible_host: 127.0.0.1
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_winrm_scheme: http
    ansible_winrm_transport: ntlm
  lint:
    name: ansible-lint

scenario:
  name: default
  converge_sequence:
    - create
    - converge
    
verifier:
  name: testinfra
  lint:
    name: flake8
  
